# Generated by Django 4.0.2 on 2022-02-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='story',
            field=models.CharField(max_length=100),
        ),
    ]
