# Generated by Django 4.0.2 on 2022-02-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_blog_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='story',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.CharField(default='image_url', max_length=2083),
        ),
    ]
