# Generated by Django 4.0.2 on 2022-02-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_story_blog_description_blog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
